components/HeroSection.tsx
components/Layout.tsx
components/navbar/ThemeSwitcher.tsx
components/navbar/index.tsx
pages/index.tsx

Update UI bits for the Hero section + Navbar 
- Fix Bug for icon theme toggle in the navbar (incorrect display)
- Add gradient display to background for dark theme 
- UI updates to match Looks Rare for the Hero description buttons
- UI updates for links hover display to match Looks Rare / Opensea 
- UI updates for header and text 
- Ensure light + dark themes work well upon updates

Feature: Minor UI Updates + Minor bug fix for themes

---

components/Footer.tsx
components/HeroSection.tsx
components/primitives/Anchor.tsx
pages/_app.tsx

I updated button animation and fixed Text Layout.

Improve Button Animation and Text Layout

---

components/quests/Quest.tsx
components/quests/QuestsGrid.tsx
components/quests/styled/index.tsx
pages/quests/index.tsx

UI page layout for quests page
This PR includes:
- Layout for quests page based on (https://zonic.app/quests)
- Quest components 
- Quests grid structure 
- Route to quests page

Feature: Quests Page UI

---

components/claim/ClaimReward.tsx
components/claim/ClaimRewardHeroBanner.tsx
components/claim/styled/index.tsx
pages/claim/index.tsx

Claims reward page on /claim/. Basic components and layout
This PR includes:
- Claim rewards page on the route path claim
- Basic claim rewards component
- Styling for page layout
- Claim hero banner for page

Feature: Basic claim rewards page

---

components/HeroSection.tsx
components/home/TrendingCollectionsTimeToggle.tsx

I updated Sell, Explore buttons and Text format.
- Changed Sell, Explore buttons more suitable for UI.
- Text format changed.

Button updated and text format

---

components/HeroSection.tsx
components/navbar/MobileSearch.tsx
components/navbar/index.tsx

Updates to navbar and hero banner
- updates to navbar and hero banner
- update broken button styling on light theme

Chore: Updates to navbar and hero banner

---

components/HeroSection.tsx
components/claim/ClaimReward.tsx
pages/claim/index.tsx

Styling Updates to claim component and hero banner 
- styling updates to claim component 
- update hero section banner

Chore: Updates to claim component and hero banner 

---

components/Footer.tsx
pages/claim/index.tsx

Chore: Update footer with link

---

hooks/useAirDropEligibleAddresses.ts
hooks/utils/index.ts

Add custom hook for claims page to check eligible addresses for airdrop

Feat: Add custom hook for claims page to check eligible addresses for airdrop

---

components/claim/ClaimReward.tsx
package.json
pages/claim/index.tsx
yarn.lock

Add dialog box to claims page if the address is not validated
- Dialog box pop up 
- Pop up logic based on address validation

Feat: Add dialog box to claims page

---

components/HeroSection.tsx
components/claim/ClaimReward.tsx
components/primitives/ToggleGroup.tsx
pages/claim/index.tsx
stitches.config.ts

Updating of our primary colors + heading updates
- Updating our app primary colors
- Heading updates

Chore: Heading and primary color updates

---

components/navbar/HamburgerMenu.tsx
components/navbar/index.tsx
pages/token/index.tsx

Add token page for NFTEarth
- Adding token page for NFTEarth

Feature: Add token page

---

pages/airdrop/index.tsx

Updated State Variable.
Updated Count Down show status.

Updated Count down Visible

---

components/Footer.tsx
components/learn-nfts/LearnGrid.tsx
components/learn-nfts/LearnHeroSection.tsx
components/learn-nfts/LearnTile.tsx
components/learn-nfts/styled/index.tsx
pages/learn-nfts/index.tsx

Add education page for NFTEarth
- Adding education page for NFTEarth
- Link to education page on footer
- components for education page
- hero banner for education page

Feature: Add NFTEarth education page

---

hooks/useCountdown.ts
pages/airdrop/index.tsx

Update Count Down Visibility State

Update Count Down Visiblity State

---

pages/learn-nfts/index.tsx

Cleaned the code of Learn NFTs page.

Changed some code in Learn NFTs

---

components/learn-nfts/LearnGrid.tsx
components/learn-nfts/LearnTile.tsx
pages/learn-nfts/index.tsx

Updated Learn NFTs page Layout.
- Text layout
- Component Style

Update Learn NFT page Layout

---

components/learn-nfts/LearnGrid.tsx

Mobile Learn NFT page

---

components/claim/ClaimReward.tsx

Fixed the light theme for Airdrop page

Fix the light theme for Airdrop page

---

components/learn-nfts/LearnCarousel.tsx
pages/learn-nfts/index.tsx

Reverted the Learn NFT page for speed
- close the carousels right now
- Add layouts of link

Revert the Learn NFT page for speed

---

components/learn-nfts/LearnGrid.tsx

Changed Layout of Learn NFT page for Mobile.

Changed Layout of Learn NFT page

---

components/learn-nfts/LearnTile.tsx

Fixed the Category Link
Just removed 404 page error.

Fixed the Category Link

---

pages/quests/index.tsx

Deleted some unnecessary component

Fixed unnecessary component

---

components/quests/templates/index.tsx

Changed Twitter Link

---

components/navbar/index.tsx

Changed Letter

---

pages/leaderboard/index.tsx

Title bigger
Made 9 quests title header bigger.

Title bigger

---

components/leaderboard/LeaderboardTable.tsx

Mobile responsive Leaderboard

---

components/Footer.tsx
components/home/ChainToggle.tsx
components/launch/LaunchHeroSection.tsx
components/primitives/ToggleGroup.tsx

Feat: add alchemy tag + other small updates

Feat: add alchemy tag + other small updates 

---

components/Footer.tsx
components/navbar/ProfileDropdown.tsx
components/quests/styled/index.tsx
pages/launch/index.tsx
pages/leaderboard/index.tsx

Chore: more ui updates

---

components/leaderboard/LeaderboardTable.tsx

Make Fake Leaderboard
- make all XP as 0 on LeaderBoard

Make Fake Leaderboard

---

pages/explore.tsx

Fix: Fix infinite load on collections page

Fix: Fix infinite load on collections page

---

components/leaderboard/LeaderboardTable.tsx
pages/collection/[chain]/[contract]/[id].tsx
pages/leaderboard/index.tsx

Chore: Leaderboard updates
